### ISSUE TITLE
希望可以开放Image preview 功能按钮定制

### ISSUE THREAD

**Issue by gexin1** [react-component/image#113]
目前tools是固定的 
有些需求无法解决
比如 下载图片
希望可以开放出来
🙏

**Comment by hamzatufailempg** [comment]
Any update on it?

**Comment by paiman-truetale** [comment]
I want to add a download button to image preview tools, but I still can not achieve it 😔

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/43075
