### ISSUE TITLE
yarn compile

### ISSUE THREAD

**Issue by xrkffgg** [react-component/image#24]
![image](https://user-images.githubusercontent.com/29775873/91859892-8d211e80-ec9d-11ea-85e7-a355c284f347.png)

---

是我本地环境的问题吗？

**Comment by shaodahong** [comment]
不是，看了下是 `rc-dialog` 升级出了问题，导出类型和以前的不一样了

**Comment by shaodahong** [comment]
https://github.com/react-component/dialog/pull/197/files

以前是默认导出

![image](https://user-images.githubusercontent.com/14831261/91861837-da05f480-ec9f-11ea-999e-a6a759835f88.png)

**Comment by xrkffgg** [comment]
@afc163 dialog 再发一版？

**Comment by xrkffgg** [comment]
😅  不能那么写吗。。。

**Comment by afc163** [comment]
本地 npm run compile 测试一下。

**Comment by xrkffgg** [comment]
更改了写法

https://github.com/react-component/dialog/blob/f7337626e5cf43e3e1213a7c892308c6fcf4cc23/src/index.ts#L4

---

dialog 恢复了

**Comment by xrkffgg** [comment]
要不 你这边更新一下~

**Comment by afc163** [comment]
没提交到 master 上？https://github.com/react-component/dialog/commits/master

**Comment by afc163** [comment]
发个 PR

**Comment by xrkffgg** [comment]
刚才看了下，之前就改成这种方式了
