### ISSUE TITLE
不能设置 Preview 组件中 img 的 crossOrigin 参数

### ISSUE THREAD

**Issue by gongrongyun** [react-component/image#243]
**场景**：页面设置 coop coep 为 same-origin, require-corp 后，所有跨域图片在显示时，必须显式设置 crossOrigin 属性

**问题**：`<Image />` 组件支持设置 crossOrigin 属性，但是没有办法在预览时将该参数传递至 `<Preview />` 组件，导致预览的图片因为跨域而不能正常显示

**预期**：将 `<Image />` 的图片参数相关设置同步至 `<Preview />` 组件中的 `<img />`

**当前版本**：`@v5.17.1`

**Comment by linxianxi** [comment]
在这里解决了 https://github.com/react-component/image/pull/247
