### ISSUE TITLE
toolbarRender 功能是不是没有发布到npm包内？

### ISSUE THREAD

**Issue by JackFeng7** [react-component/image#251]
toolbarRender 功能是不是没有发布到5.17.1版本里边？
![image](https://github.com/react-component/image/assets/52450733/cabaa89a-37ed-4167-bca8-94d83eda7640)

**Comment by linxianxi** [comment]
还没

**Comment by JackFeng7** [comment]
> 有计划什么时候发布一个新版本吗？因为我需要自己扩展一部分操作，如下载。

另外，我想问一下，有考虑将工具的内置能力开放出来吗？比如，我要做恢复1:1的比例时，我需要能够直接操作图片的某些属性

**Comment by linxianxi** [comment]
讲详细点

**Comment by afc163** [comment]
已经发布了。
