### ISSUE TITLE
Only load preview image if the preview is actually open

### ISSUE THREAD

**Issue by paulvonallwoerden** [react-component/image#263]
# Current behavior

The provided preview.src is downloaded as soon as the component is mounted.

# Expected behavior

The provided preview.src should only be downloaded if the preview is actually open. If many image elements are present on a page all preview images (which can be large in size) will be downloaded. However, maybe the user will only preview some of the images.

# Suggested resolution

Add some kind of option like (`preview.lazy`) to only download the preview src if the preview is actually opened.

# Thoughts

I think it would be a nice addition to this wonderful component. Would a PR that adds this feature be appreciated?

**Comment by paulvonallwoerden** [comment]
I was able to implement the expected behavior using `onVisibleChange`. See:

```ts
export interface LazyPreviewImageProps {
    width?: number
    height?: number
    src: string
    previewSrc: string
}

export function LazyPreviewImage(props: LazyPreviewImageProps) {
    const { width, height, src, previewSrc, borderRadius } = props
    const [previewVisible, setPreviewVisible] = useState(false)
    const actualPreviewSrc = useMemo(
        () => {
            if (!previewVisible) {
                return src
            }

            return previewSrc
        },
        [previewVisible, previewSrc, src],
    )

    return (
        <Image
            width={width}
            height={height}
            src={src}
            preview={{
                src: actualPreviewSrc,
                onVisibleChange: (visible) => setPreviewVisible(visible),
            }}
        />
    )
}
```

It think it would still be nice to support this feature natively :-)

For anyone watching: I'll publish this code as MIT - feel free to copy 👍

**Comment by yoyo837** [comment]
Close by #265
