### ISSUE TITLE
Version of rc-util dependency should be updated

### ISSUE THREAD

**Issue by alex-golubtsov** [react-component/image#270]
`"rc-util": "^5.0.6"` should be updated to at least `"rc-util": "^5.26.0"`.
`isEqual` was introduced in 5.26.0. Being used [here](https://github.com/react-component/image/blob/v7.0.0-2/src/hooks/useImageTransform.ts#L2)

**Comment by afc163** [comment]
https://github.com/react-component/image/releases/tag/v7.0.0
