### ISSUE TITLE
preview-operations-wrapper 在close后不会自动销毁

### ISSUE THREAD

**Issue by zwwill** [react-component/image#325]
由5.2.5 升级到7.2.0 遇到一个问题，图片预览后 `preview-operations-wrapper` 不会自动销毁。RT。
![image](https://github.com/react-component/image/assets/20720117/bb06bf0e-2d92-49e4-b45c-2b1cdb22be4e)

**Comment by afc163** [comment]
现在官网实测貌似会自动销毁了。https://ant.design/components/image-cn
