### ISSUE TITLE
Image.PreviewGroup套在Carousel组件外面，Image注册预览图片地址有问题

### ISSUE THREAD

**Issue by Stoneleee** [react-component/image#98]
场景：因为需要实现轮播图，然后轮播的图片可以进行多图预览
代码：
```tsx
<Image.PreviewGroup>
      <Carousel
          ref={carouselRef}
          easing="fade"
          afterChange={handleCarouselChange}
          dots={false}
      >
          {imgUrls.map((url: string) => (
              <div className="preview_img_wrap" key={url}>
                  <Image
                      src={url}
                      preview={{
                          mask: null,
                      }}
                      fallback={errorImage}
                      placeholder={true}
                  />
              </div>
          ))}
      </Carousel>
  </Image.PreviewGroup>
```
问题：
将Group写在Carousel外面，导致图片地址注册重复了，实际图片只有23个
![image](https://user-images.githubusercontent.com/28681019/122362029-5e550a00-cf8a-11eb-96a0-c739c1207ebc.png)

请问这种情况怎么处理呢 @shaodahong

**Comment by shaodahong** [comment]
> 场景：因为需要实现轮播图，然后轮播的图片可以进行多图预览
> 代码：
> 
> ```tsx
> <Image.PreviewGroup>
>       <Carousel
>           ref={carouselRef}
>           easing="fade"
>           afterChange={handleCarouselChange}
>           dots={false}
>       >
>           {imgUrls.map((url: string) => (
>               <div className="preview_img_wrap" key={url}>
>                   <Image
>                       src={url}
>                       preview={{
>                           mask: null,
>                       }}
>                       fallback={errorImage}
>                       placeholder={true}
>                   />
>               </div>
>           ))}
>       </Carousel>
>   </Image.PreviewGroup>
> ```
> 
> 问题：
> 将Group写在Carousel外面，导致图片地址注册重复了，实际图片只有23个
> ![image](https://user-images.githubusercontent.com/28681019/122362029-5e550a00-cf8a-11eb-96a0-c739c1207ebc.png)
> 
> 请问这种情况怎么处理呢 @shaodahong

大概猜测了一下 Carousel 为了实现轮播图的效果会复制子元素

**Comment by Stoneleee** [comment]
ow，直击要害，看轮播图生成的节点确实是数量一致。

**Comment by Stoneleee** [comment]
但是看了下，官方文档中基本没有可用的api进行处理，请问有什么建议吗

**Comment by shaodahong** [comment]
分开处理，然后隐藏 image group 显示的图片，点击轮播图片的时候对 imageGroup 受控展示

**Comment by Stoneleee** [comment]
最后一个问题，image group预览切换的索引没有办法拿到，看代码在onClose没有给返

**Comment by F-loat** [comment]
遇到过类似的问题，使用了另一个库做预览功能，而且更美观一些 https://github.com/Caldis/react-zmage
